In [14]:
import numpy as np
import gym
import random

In [15]:
env = gym.make('FrozenLake-v0')

In [16]:
action_space = env.action_space.n
state_space = env.observation_space.n

print(action_space, state_space)

4 16


In [17]:
qtable = np.zeros((state_space, action_space))

In [22]:
num_episodes = 20000
num_steps = 99
alpha = 0.9
gamma = 0.95

epsilon = 1.0
min_epsilon = 0.01
max_epsilon = 1.0
decay_rate = 0.001
rewards = []

In [23]:
for episode in range(num_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    
    for step in range(num_steps):
        tradeoff = random.uniform(0,1)
        
        if tradeoff > epsilon:
            action = np.argmax(qtable[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        qtable[state,action] = qtable[state,action] + alpha*(reward + \
                                    gamma*np.max(qtable[new_state,:]) - qtable[state,action])
        
        total_rewards += reward
        state = new_state
    
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)
    
print("Score over time: ", sum(rewards)/num_episodes)
print(qtable)

Score over time:  0.3967
[[1.73671882e-01 4.96264327e-02 3.04975254e-01 4.23432254e-02]
 [7.70606462e-06 3.11036439e-05 4.69457889e-03 2.05316459e-01]
 [1.24655256e-01 1.37915624e-02 1.61041816e-02 1.57685418e-02]
 [1.14120037e-03 3.84199651e-03 8.52510639e-05 1.59168802e-02]
 [6.37460095e-01 4.58106868e-03 5.01030084e-02 1.48248901e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.42971635e-03 1.32770159e-05 1.83216841e-02 1.50865225e-07]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.89081211e-04 3.45957256e-02 1.49695254e-02 6.16136384e-01]
 [7.79684614e-06 7.88558323e-01 8.96393165e-02 2.93000732e-03]
 [9.53553981e-02 9.22194702e-04 1.76534046e-01 1.83460174e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.45532381e-02 4.69550957e-03 9.19550472e-01 8.92848379e-02]
 [1.03061711e-01 9.97932929e-01 5.82217398e-01 7.24059590e-02]
 [0.00000000e+00 0.00000000e+0

In [24]:
env.reset()

total = 0
test_episodes = 5

for episode in range(test_episodes):
    step = 0
    state = env.reset()
    done = False
    print()
    print("Episode", episode)
    
    for step in range(num_steps):
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        if done:
            env.render()
            print("Reward is: ", reward)
        
        state = new_state
        total += reward

print("Score over time: ", total/test_episodes)
env.close()


Episode 0
  (Down)
SFFF
FHFH
FFFH
HFFG
Reward is:  1.0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  0
  (Left)
SFFF
FHFH
FFFH
HFFG
Reward is:  